liste_commentaire = [
    "L'école manque de professionnalisme dans son approche pédagogique.",
    "Le système éducatif de l'école est obsolète et peu efficace.",
    "Le personnel enseignant est mal formé et peu motivé.",
    "L'école néglige le bien-être et la sécurité des élèves.",
    "Les installations de l'école sont vétustes et mal entretenues.",
    "Le programme scolaire est désorganisé et manque de rigueur.",
    "L'administration de l'école est inefficace et peu réceptive aux besoins des élèves.",
    "Les frais de scolarité sont excessifs par rapport à la qualité de l'éducation offerte.",
    "L'école favorise la discrimination et l'exclusion plutôt que l'inclusion et la diversité.",
    "Les méthodes d'enseignement de l'école sont dépassées et peu adaptées aux besoins des élèves.",
    "L'école manque de ressources et d'infrastructures adéquates pour soutenir l'apprentissage des élèves.",
    "Le climat scolaire est hostile et peu propice à l'épanouissement des élèves.",
    "L'école ne respecte pas les normes de sécurité et d'hygiène.",
    "Les enseignants ne sont pas disponibles pour aider les élèves en difficulté.",
    "L'administration de l'école est opaque et peu transparente dans ses décisions.",
    "Les parents sont mal informés sur la vie scolaire de leurs enfants et ont peu de moyens d'interagir avec l'école.",
    "L'école ne propose pas assez d'activités extrascolaires pour enrichir l'expérience des élèves.",
    "Les élèves sont souvent livrés à eux-mêmes sans encadrement adéquat de la part du personnel.",
    "L'école privilégie la performance académique au détriment du bien-être émotionnel des élèves.",
    "Le système disciplinaire de l'école est injuste et arbitraire, favorisant la répression plutôt que la résolution des conflits.",
    "L'école ne parvient pas à répondre aux besoins spécifiques des élèves en situation de handicap ou d'apprentissage difficile.",
    "Le manque de diversité culturelle dans le corps enseignant nuit à la représentativité et à l'inclusivité de l'école.",
    "Les méthodes d'évaluation de l'école sont peu fiables et peu équitables, favorisant la sélection plutôt que l'apprentissage.",
    "L'école ne tient pas compte des différences individuelles des élèves dans son approche pédagogique, créant ainsi un environnement d'apprentissage peu adapté.",
    "Le manque d'investissement de l'école dans le développement professionnel de son personnel nuit à la qualité de l'enseignement.",
    "Les conflits internes au sein de l'équipe éducative créent un climat de tension et d'instabilité préjudiciable à l'apprentissage des élèves.",
    "Les méthodes d'enseignement de l'école sont dépassées et peu interactives, ce qui rend l'apprentissage ennuyeux pour les élèves.",
    "Le manque de suivi individualisé des élèves conduit à un décrochage scolaire généralisé.",
    "Les locaux de l'école sont mal entretenus et peu accueillants pour les élèves.",
    "L'école ne prend pas en compte les besoins spécifiques des élèves internationaux, les laissant se débrouiller seuls dans un environnement étranger.",
    "Les enseignants manquent d'empathie envers les élèves et sont souvent autoritaires dans leur approche pédagogique.",
    "L'école est peu inclusive et ne prend pas en compte la diversité culturelle et linguistique de ses élèves.",
    "Le manque de communication entre l'école et les parents conduit à une incompréhension généralisée des besoins des élèves.",
    "Les activités parascolaires sont inexistantes ou peu attrayantes pour les élèves, ce qui limite leur épanouissement hors du cadre scolaire.",
    "L'école manque de vision à long terme et se contente de solutions temporaires pour résoudre les problèmes rencontrés.",
    "Le manque d'investissement de l'école dans les nouvelles technologies nuit à la préparation des élèves aux défis du XXIe siècle.",
    "Les élèves sont souvent mis en compétition les uns contre les autres, ce qui crée un environnement d'apprentissage stressant et peu collaboratif.",
    "L'école ne parvient pas à motiver les élèves et à susciter leur intérêt pour les différentes matières enseignées.",
    "Les évaluations sont trop centrées sur la mémorisation des connaissances plutôt que sur la compréhension et l'application des concepts.",
    "L'école ne prend pas en compte les besoins émotionnels et sociaux des élèves, les laissant souvent seuls face à leurs problèmes.",
    "Le manque de diversité dans les programmes d'études limite les possibilités d'apprentissage des élèves.",
    "Les élèves ne se sentent pas en sécurité dans l'environnement scolaire en raison de l'absence de mesures efficaces de lutte contre le harcèlement et l'intimidation.",
    "L'école ne parvient pas à impliquer activement les élèves dans leur propre apprentissage, les laissant passifs et désintéressés.",
    "Les enseignants ne reçoivent pas suffisamment de soutien de la part de l'administration pour mettre en œuvre des pratiques pédagogiques innovantes et efficaces.",
    "Les élèves ne se sentent pas valorisés et respectés en tant qu'individus au sein de l'école, ce qui nuit à leur estime de soi et à leur motivation.",
    "L'école ne parvient pas à offrir un environnement d'apprentissage stimulant et enrichissant qui encourage la curiosité et la créativité des élèves.",
    "Les élèves sont souvent confrontés à des retards dans la mise en œuvre des programmes d'études en raison du manque de planification de l'administration.",
    "L'école ne parvient pas à intégrer efficacement les nouvelles technologies dans son sense" ]
